remote_theme: just-the-docs/just-the-docs

search_enabled: true

color_scheme: dark

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

title: Sunset Lodge Support
description: A support website for Sunset Lodge
baseurl: "/support"
url: "https://sunsetlodge.github.io"
